# Generated by Django 4.1.7 on 2023-05-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.IntegerField(db_column='ID_ALUMNO', primary_key=True, serialize=False)),
                ('nie', models.CharField(blank=True, db_column='NIE', max_length=7, null=True)),
                ('apellidos_alumno', models.CharField(blank=True, db_column='APELLIDOS_ALUMNO', max_length=50, null=True)),
                ('nombres_alumno', models.CharField(blank=True, db_column='NOMBRES_ALUMNO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='NOMBRE_CATEGORIA', max_length=30)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.IntegerField(db_column='ID_DOCENTE', primary_key=True, serialize=False)),
                ('numidentificacion', models.CharField(blank=True, db_column='NUMIDENTIFICACION', max_length=8, null=True)),
                ('dui', models.CharField(blank=True, db_column='DUI', max_length=8, null=True)),
                ('nombre_docente', models.CharField(blank=True, db_column='NOMBRE_DOCENTE', max_length=50, null=True)),
                ('apellido_docente', models.CharField(blank=True, db_column='APELLIDO_DOCENTE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.IntegerField(db_column='ID_EVALUACION', primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(blank=True, db_column='NOMBRE_EVALUACION', max_length=50, null=True)),
                ('porcentaje', models.CharField(blank=True, db_column='PORCENTAJE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacionalumno',
            fields=[
                ('id_evaluacionalumno', models.IntegerField(db_column='ID_EVALUACIONALUMNO', primary_key=True, serialize=False)),
                ('nota', models.FloatField(db_column='NOTA')),
            ],
            options={
                'db_table': 'evaluacionalumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichaalumno',
            fields=[
                ('id_fichaalumno', models.IntegerField(db_column='ID_FICHAALUMNO', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fichaalumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichadocente',
            fields=[
                ('id_fichadocente', models.IntegerField(db_column='ID_FICHADOCENTE', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fichadocente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.IntegerField(db_column='ID_GRADO', primary_key=True, serialize=False)),
                ('grado', models.CharField(blank=True, db_column='GRADO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradoseccion',
            fields=[
                ('id_gradoseccion', models.IntegerField(db_column='ID_GRADOSECCION', primary_key=True, serialize=False)),
                ('turno_gradoseccion', models.CharField(db_column='TURNO_GRADOSECCION', max_length=1)),
            ],
            options={
                'db_table': 'gradoseccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradoseccionmateria',
            fields=[
                ('id_gradoseccionmateria', models.IntegerField(db_column='ID_GRADOSECCIONMATERIA', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gradoseccionmateria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.IntegerField(db_column='ID_MATERIA', primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(blank=True, db_column='NOMBRE_MATERIA', max_length=100, null=True)),
            ],
            options={
                'db_table': 'materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.IntegerField(db_column='ID_SECCION', primary_key=True, serialize=False)),
                ('seccion', models.CharField(blank=True, db_column='SECCION', max_length=1, null=True)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id_trimestre', models.IntegerField(db_column='ID_TRIMESTRE', primary_key=True, serialize=False)),
                ('trimestre', models.CharField(blank=True, db_column='TRIMESTRE', max_length=50, null=True)),
                ('anio', models.CharField(blank=True, db_column='ANIO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'trimestre',
                'managed': False,
            },
        ),
    ]
