# Generated by Django 4.1.7 on 2023-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadenotas', '0002_promediomateria_delete_fichaalumno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promediomateria',
        ),
    ]
